name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa $SERVER_IP >> ~/.ssh/known_hosts

        ssh -o StrictHostKeyChecking=no root@$SERVER_IP << 'EOF'

        # Parameters
        APP_DIR_ROOT=/root/projects/wiki
        APP_DIR=/root/projects/wiki/src

        echo "Pull the repository..."
        cd $APP_DIR
        git reset --hard
        git clean -fd
        git pull --rebase

        # Copy .env file
        cp $APP_DIR_ROOT/.env $APP_DIR/.env
        cp $APP_DIR_ROOT/docker-compose.yml $APP_DIR/docker-compose.yml

        echo "Restarting the containers..."

        docker-compose down || true
        docker-compose up -d || {
          echo "Error: Failed to start the containers."
          exit 1
        }

        echo "Deployment successful!"
        EOF