name: Deploy Flask App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to server
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts || {
          echo "Error: Failed to add the SSH key to known_hosts."
          exit 1
        }

        ssh -p ${{ secrets.SERVER_PORT }} -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'

        # Parameters
        APP_DIR_ROOT=/${{ secrets.SERVER_USER }}/projects/wiki
        APP_DIR=/${{ secrets.SERVER_USER }}/projects/wiki/src

        echo "Pull the repository..."
        cd $APP_DIR
        git reset --hard
        git clean -fd
        git pull --rebase

        # Copy .env file
        cp $APP_DIR_ROOT/.env $APP_DIR/.env
        cp $APP_DIR_ROOT/docker-compose.yml $APP_DIR/docker-compose.yml

        echo "Restarting the containers..."
        docker stop r2wiki_flask
        docker rm r2wiki_flask
        
        docker-compose up -d || {
          echo "Error: Failed to start the containers."
          exit 1
        }

        echo "Deployment successful!"
        EOF